# Generated by Django 4.2.6 on 2023-12-16 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_animal', models.IntegerField(verbose_name='No. Animal')),
                ('codigo', models.IntegerField(verbose_name='Codigo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('vaca', 'Vaca'), ('toro', 'Toro')], max_length=16, verbose_name='Genero')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('partos', models.IntegerField(verbose_name='Partos')),
                ('desendencia', models.IntegerField(verbose_name='Desendencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('propietario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
        ),
    ]
